# -*- coding: utf-8 -*-
"""GDGoCML_Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxnz8XobjFWRrq5B8nIuwBehQCBqSwQO
"""

# Membuat file dummy untuk contoh
konten = """
Ini adalah data hasil pengukuran.
Nilai pertama adalah 10 dan nilai kedua adalah 23.
Ada juga angka negatif seperti -4 dan angka besar 105.
Semoga berhasil!
"""

with open('data_angka.txt', 'w') as f:
    f.write(konten)

print("File 'data_angka.txt' berhasil dibuat!")

import re
import os

def cek_ganjil_genap(nama_file):
    # Cek apakah file ada
    if not os.path.exists(nama_file):
        print(f"Error: File '{nama_file}' tidak ditemukan.")
        return

    print(f"--- Menganalisis file: {nama_file} ---")

    try:
        # Membaca isi file
        with open(nama_file, 'r') as file:
            text = file.read()

        # Mencari semua angka dalam teks menggunakan Regex
        # r'-?\d+' artinya: mencari angka (d+) yang mungkin ada tanda minus (-?)
        angka_ditemukan = re.findall(r'-?\d+', text)

        if not angka_ditemukan:
            print("Tidak ada angka yang ditemukan dalam file ini.")
            return

        # Loop untuk cek setiap angka
        results = []
        for angka_str in angka_ditemukan:
            angka = int(angka_str)
            status = "Genap" if angka % 2 == 0 else "Ganjil"

            # Menyimpan hasil agar rapi
            results.append([angka, status])
            print(f"Angka: {angka} adalah {status}")

    except Exception as e:
        print(f"Terjadi kesalahan: {e}")

# --- EKSEKUSI KODE ---
nama_file_target = 'data_angka.txt'
cek_ganjil_genap(nama_file_target)