# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOfKJLbgNkO0MEGpZJZ9Pdpmxvy5-1nv

Variable
"""

#Python Variables
nama = "budi"
umur = 21
print("Nama:", nama)
print(umur)
nilai_y=15
print (nilai_y)

data_integer = 11
print("data:", data_integer, "type:", type(data_integer))

data_float = 1.5
print("data:", data_float, "type:", type(data_float))

data_strings= "ucup"
print("data", data_strings, "type:", type(data_strings))

#List
mix = [1, "halo", True, 4.14]
print(mix)

buah = ["pisang", "alpukat", "jambu"]
buah.append("mangga")
print(buah)

print(len(buah))

#Tuple
indentitatas = ("sisti", 20, "jakarta")
print(indentitatas[0])

#Set
buah = {"pisang", "apel", "jeruk", "jeruk"}
print(buah)

#Dictionary

orang = {
    "nama": "budi",
    "umur": 20,
    "alamat": "jakarta"
}
print (orang["umur"])
orang["alamat"] = "Bandung"
print(orang)

#Casting

a = int(3.99)
b = float(3)
c = str(3)

print(a, b, c)

x = 10
y = 5

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x % y)

x = 20
y = 2

print("x == y:", x == y)
print("x != y:", x != y)
print("x > y:", x > y)
print("x < y:", x < y)
print("x <= y:", x <= y)
print("x >= y:", x >= y)

#Menulis file
file = open("test.txt", 'w')
file.write("Halo Dunia")
file.close()

with open("test.txt", "r") as file:
    print(file.read())

with open("test.txt", "a") as file:
    file.write("\nHalo Telkom")

jml_siswa = int(input("Masukkan Jumlah Siswa: "))

if jml_siswa > 10:
  print("Jumlah siswa terlalu banyak")

nilai = int(input("Masukan nilai siswwa:"))
kkm = 75

if(nilai >= kkm):
  print("Siswa lulus")
else:
  print("siswa tidak lulus")

nilai = int(input("Masukan nilai siswa:"))
if(90 <= nilai <= 100):
  print("A")
elif(80 <= nilai < 90):
  print("B")
elif(70 <= nilai < 80):
  print("C")
elif(60 <= nilai < 70):
  print("D")
else:
  print("E")